dist: xenial
language: scala
scala:
   - 2.12.12
jdk:
   - openjdk8
before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache     -name "ivydata-*.properties" -print -delete
  - find $HOME/.cache/coursier -name "*.lock"               -print -delete
  - find $HOME/.sbt            -name "*.lock"               -print -delete
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.cache/coursier
    - $HOME/.sbt
